name: Deploy to EKS

on:
  push:
    branches:
      - main
      - refactor/terraform-modules

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::797671034493:role/eks-observability-github-actions-role
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # -------- FASTAPI --------
      - name: Build FastAPI Docker image
        run: |
          docker build -t fastapi-app ./app

      - name: Tag FastAPI Docker image
        run: |
          docker tag fastapi-app:latest 797671034493.dkr.ecr.us-east-1.amazonaws.com/eks-observability-fastapi:latest

      - name: Push FastAPI Docker image to ECR
        run: |
          docker push 797671034493.dkr.ecr.us-east-1.amazonaws.com/eks-observability-fastapi:latest

      # -------- WEBSITE --------
      - name: Build Website Docker image
        run: |
          docker build -t website ./website

      - name: Tag Website Docker image
        run: |
          docker tag website:latest 797671034493.dkr.ecr.us-east-1.amazonaws.com/eks-observability-website:latest

      - name: Push Website Docker image to ECR
        run: |
          docker push 797671034493.dkr.ecr.us-east-1.amazonaws.com/eks-observability-website:latest

      # -------- EKS ACCESS --------
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name eks-observability-cluster

      - name: Install Helm
        uses: azure/setup-helm@v4

      # -------- DEPLOYMENTS --------
      - name: Deploy FastAPI using Helm
        run: |
          helm upgrade --install fastapi-app ./helm/fastapi \
            --namespace default \
            --set image.repository=797671034493.dkr.ecr.us-east-1.amazonaws.com/eks-observability-fastapi \
            --set image.tag=latest

      - name: Deploy Website using Helm
        run: |
          helm upgrade --install website ./helm/website \
            --namespace default
