name: Deploy to EKS

on:
  push:
    branches:
      - main
      - refactor/terraform-modules

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::797671034493:role/eks-observability-github-actions-role
          aws-region: us-east-1
